import { Router, type IRouter, type Request, type Response } from "express";
import PDFDocument from "pdfkit";
import QRCode from "qrcode";
import { db, casesTable } from "@workspace/db";
import { eq } from "drizzle-orm";
import {
  parseInboundPayload,
  handleWhatsAppInbound,
} from "../../services/whatsapp/inbound";
import { sendCaseSummary } from "../../services/whatsapp/outbound";
import { verifyTwilioSignature } from "../../middlewares/twilioWebhook";

const router: IRouter = Router();

/**
 * Twilio WhatsApp inbound webhook. We respond immediately with empty TwiML
 * (Twilio's required ack) and process the message asynchronously, sending
 * the structured reply via the REST API once the pipeline finishes.
 */
router.post("/inbound", verifyTwilioSignature, async (req: Request, res: Response) => {
  // Ack first so Twilio doesn't retry while we work.
  res.set("Content-Type", "application/xml");
  res.send(`<?xml version="1.0" encoding="UTF-8"?>\n<Response/>`);

  const payload = parseInboundPayload(
    req.body as Record<string, string | undefined>,
  );
  try {
    await handleWhatsAppInbound(payload, {
      onComplete: (caseId, fromPhone) => sendCaseSummary(caseId, fromPhone),
    });
  } catch (err) {
    req.log.warn({ err }, "whatsapp inbound handler failed");
  }
});

/**
 * Generate a PNG QR code that joins the Twilio WhatsApp Sandbox.
 *
 * Twilio sandbox uses the canonical "join <code>" SMS pattern; we build a
 * `https://wa.me/<number>?text=join+<code>` deep link so scanning opens
 * WhatsApp pre-populated with the join command.
 */
router.get("/qrcode", async (req: Request, res: Response) => {
  const phoneRaw = process.env.TWILIO_WHATSAPP_NUMBER ?? "";
  const code = process.env.TWILIO_WHATSAPP_SANDBOX_CODE ?? "lexor";
  const phone = phoneRaw.replace(/^whatsapp:/, "").replace(/\D/g, "");
  const url = phone
    ? `https://wa.me/${phone}?text=${encodeURIComponent(`join ${code}`)}`
    : `https://wa.me/?text=${encodeURIComponent(`join ${code}`)}`;
  try {
    const png = await QRCode.toBuffer(url, {
      width: 320,
      margin: 1,
      color: { dark: "#ffffff", light: "#0b0d12" },
    });
    res.set("Content-Type", "image/png");
    res.set("Cache-Control", "public, max-age=600");
    res.send(png);
  } catch (err) {
    req.log.warn({ err }, "qrcode generation failed");
    res.status(500).end();
  }
});

/**
 * Public PDF render of a case's response letter — used as the WhatsApp
 * outbound `mediaUrl`. Twilio fetches the URL server-side, so it must be
 * publicly reachable; we keep it read-only and content-addressed by case
 * id (UUID is unguessable enough to act as a capability token for v1).
 */
router.get("/cases/:id/letter.pdf", async (req: Request, res: Response) => {
  const idRaw = req.params.id;
  const id = typeof idRaw === "string" ? idRaw : "";
  if (!/^[0-9a-f-]{36}$/i.test(id)) {
    res.status(400).send("invalid id");
    return;
  }
  const [row] = await db
    .select({
      responseLetter: casesTable.responseLetter,
      vertical: casesTable.vertical,
      jurisdiction: casesTable.jurisdiction,
    })
    .from(casesTable)
    .where(eq(casesTable.id, id))
    .limit(1);
  if (!row?.responseLetter) {
    res.status(404).send("not ready");
    return;
  }
  const letter = row.responseLetter as {
    plainText?: string;
    citations?: Array<{ label: string; url: string }>;
  };
  res.set("Content-Type", "application/pdf");
  res.set("Content-Disposition", `inline; filename="lexor-${id.slice(0, 8)}.pdf"`);
  res.set("Cache-Control", "public, max-age=300");
  const doc = new PDFDocument({ size: "LETTER", margin: 64 });
  doc.pipe(res);
  doc.font("Helvetica-Bold").fontSize(18).text("Lexor — Response Letter");
  doc.moveDown(0.3);
  doc
    .font("Helvetica-Oblique")
    .fontSize(10)
    .fillColor("#666")
    .text(
      `Type: ${row.vertical ?? "other"}${
        row.jurisdiction ? ` · ${row.jurisdiction}` : ""
      } · Generated by an AI assistant — not legal advice.`,
    );
  doc.moveDown(1).fillColor("#111").font("Helvetica").fontSize(11);
  doc.text(letter.plainText ?? "(letter unavailable)", { align: "left" });
  if (letter.citations && letter.citations.length > 0) {
    doc.moveDown(1.2).font("Helvetica-Bold").fontSize(12).text("Citations");
    doc.font("Helvetica").fontSize(10).fillColor("#333");
    for (const c of letter.citations) {
      doc.text(`• ${c.label} — ${c.url}`);
    }
  }
  doc.end();
});

export default router;
