CREATE EXTENSION IF NOT EXISTS vector;
-- Briefcase initial migration. Generated by drizzle-kit and edited to (1)
-- enable pgvector before any vector(1536) columns and (2) install the
-- run_events monotonic-idx trigger after the table is created.

CREATE TABLE "artifacts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"run_id" uuid NOT NULL,
	"subagent" text NOT NULL,
	"kind" text NOT NULL,
	"data" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "case_files" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"case_id" uuid NOT NULL,
	"source_type" text NOT NULL,
	"drive_file_id" text,
	"name" text NOT NULL,
	"mime" text,
	"size_bytes" bigint,
	"sha256" char(64),
	"ocr_text" text,
	"detected_language" text,
	"embedding" vector(1536),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "case_files_source_type_check" CHECK ("case_files"."source_type" in ('upload','drive','scan','audio'))
);
--> statement-breakpoint
CREATE TABLE "cases" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"role_pack" text NOT NULL,
	"jurisdiction_context" jsonb,
	"language" text,
	"status" text DEFAULT 'created' NOT NULL,
	"deleted_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "cases_role_pack_check" CHECK ("cases"."role_pack" in ('defender','detective')),
	CONSTRAINT "cases_status_check" CHECK ("cases"."status" in ('created','ingesting','ready','running','prepared','error','deleted'))
);
--> statement-breakpoint
CREATE TABLE "citations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"run_id" uuid NOT NULL,
	"artifact_kind" text NOT NULL,
	"source_type" text NOT NULL,
	"source_id" text,
	"span" jsonb,
	"verified_quote" text,
	"verified_at" timestamp with time zone,
	CONSTRAINT "citations_source_type_check" CHECK ("citations"."source_type" in ('pdf','image','audio','video','url','transcript'))
);
--> statement-breakpoint
CREATE TABLE "prep_items" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"case_id" uuid NOT NULL,
	"artifact_id" uuid NOT NULL,
	"item_key" text NOT NULL,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "run_events" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"run_id" uuid NOT NULL,
	"idx" integer NOT NULL,
	"type" text NOT NULL,
	"payload" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "run_events_idx_nonneg" CHECK ("run_events"."idx" >= 0)
);
--> statement-breakpoint
CREATE TABLE "runs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"case_id" uuid NOT NULL,
	"role_pack" text NOT NULL,
	"goal" text,
	"idempotency_key" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"cancelled" boolean DEFAULT false NOT NULL,
	"started_at" timestamp with time zone,
	"completed_at" timestamp with time zone,
	"error_message" text,
	CONSTRAINT "runs_idempotency_key_unique" UNIQUE("idempotency_key"),
	CONSTRAINT "runs_status_check" CHECK ("runs"."status" in ('pending','running','completed','cancelled','error'))
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"display_name" text,
	"email" text,
	"google_refresh_token" "bytea",
	"google_refresh_token_iv" "bytea",
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "agent_traces" (
	"run_id" uuid NOT NULL,
	"idx" integer NOT NULL,
	"node_path" text,
	"tokens_in" integer,
	"tokens_out" integer,
	"latency_ms" integer,
	"cost_usd" numeric(10, 6),
	CONSTRAINT "agent_traces_run_id_idx_pk" PRIMARY KEY("run_id","idx")
);
--> statement-breakpoint
CREATE TABLE "contradictions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"run_id" uuid NOT NULL,
	"claim" text,
	"source_a" jsonb,
	"source_b" jsonb,
	"severity" text,
	"type" text,
	"explanation" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "contradictions_severity_check" CHECK ("contradictions"."severity" in ('low','medium','high')),
	CONSTRAINT "contradictions_type_check" CHECK ("contradictions"."type" in ('timestamp','identity','sequence','fact'))
);
--> statement-breakpoint
CREATE TABLE "courtroom_sessions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" text,
	"case_id" uuid,
	"started_at" timestamp with time zone,
	"ended_at" timestamp with time zone,
	"event_count" integer DEFAULT 0
);
--> statement-breakpoint
CREATE TABLE "disclosure_gaps" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"run_id" uuid NOT NULL,
	"expected_item" text,
	"basis_for_expectation" text,
	"rule_citation" jsonb,
	"request_status" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "disclosure_gaps_request_status_check" CHECK ("disclosure_gaps"."request_status" in ('not_requested','requested','received','withheld'))
);
--> statement-breakpoint
CREATE TABLE "jury_simulations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"run_id" uuid NOT NULL,
	"jurors" jsonb,
	"deliberation" jsonb,
	"verdict_distribution" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "objection_events" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"session_id" uuid NOT NULL,
	"idx" integer NOT NULL,
	"transcript" text,
	"suggestion" text,
	"rule_citation" jsonb,
	"captured_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "plea_simulations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"run_id" uuid NOT NULL,
	"charge" text,
	"jurisdiction" text,
	"trial_distribution" jsonb,
	"plea_distribution" jsonb,
	"summary" text,
	"dataset_citations" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "prosecution_runs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"parent_run_id" uuid NOT NULL,
	"output" jsonb,
	"weakness_report" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "rights_findings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"run_id" uuid NOT NULL,
	"right_category" text,
	"jurisdiction_rule" text,
	"evidence_from_case" jsonb,
	"cited_authority" jsonb,
	"severity" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "rights_findings_severity_check" CHECK ("rights_findings"."severity" in ('low','medium','high'))
);
--> statement-breakpoint
CREATE TABLE "run_branches" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"parent_run_id" uuid NOT NULL,
	"branched_at_idx" integer,
	"edited_inputs" jsonb,
	"child_run_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "agent_costs" (
	"run_id" uuid PRIMARY KEY NOT NULL,
	"total_usd" numeric(10, 6),
	"by_model" jsonb,
	"by_tool" jsonb,
	"by_phase" jsonb,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "agent_messages" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"run_id" uuid NOT NULL,
	"idx" integer NOT NULL,
	"from_agent" text,
	"to_agent" text,
	"body" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "audit_bundles" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"run_id" uuid NOT NULL,
	"bundle_uri" text,
	"signature" text,
	"signing_key_id" text,
	"size_bytes" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cost_ceilings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"scope" text,
	"scope_id" text,
	"monthly_usd" numeric(10, 2),
	"hard_stop" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "model_routing_decisions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"run_id" uuid NOT NULL,
	"idx" integer NOT NULL,
	"task_kind" text,
	"candidates" jsonb,
	"chosen_model" text,
	"rationale" text,
	"cost_usd" numeric(10, 6),
	"latency_ms" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "policy_drops" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"run_id" uuid NOT NULL,
	"subagent" text,
	"rule" text,
	"dropped_payload" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "prompt_versions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"prompt_key" text NOT NULL,
	"version" text NOT NULL,
	"content" text,
	"variant" text,
	"is_active" boolean DEFAULT false NOT NULL,
	"metrics" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "quality_judgments" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"run_id" uuid NOT NULL,
	"subagent" text,
	"rubric" jsonb,
	"score" numeric(3, 2),
	"rationale" text,
	"retried" boolean,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "replay_cases" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"run_id" uuid,
	"fixture_uri" text,
	"expected" jsonb,
	"tags" text[],
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "semantic_cache" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"cache_key" text NOT NULL,
	"prompt_embedding" vector(1536),
	"result" jsonb,
	"hit_count" integer DEFAULT 0 NOT NULL,
	"cost_saved_usd" numeric(10, 6) DEFAULT '0',
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_used_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "semantic_cache_cache_key_unique" UNIQUE("cache_key")
);
--> statement-breakpoint
CREATE TABLE "speculative_branches" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"run_id" uuid NOT NULL,
	"subagent" text,
	"speculation" text,
	"output" jsonb,
	"started_at" timestamp with time zone,
	"decided_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "artifacts" ADD CONSTRAINT "artifacts_run_id_runs_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."runs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "case_files" ADD CONSTRAINT "case_files_case_id_cases_id_fk" FOREIGN KEY ("case_id") REFERENCES "public"."cases"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cases" ADD CONSTRAINT "cases_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "citations" ADD CONSTRAINT "citations_run_id_runs_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."runs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "prep_items" ADD CONSTRAINT "prep_items_case_id_cases_id_fk" FOREIGN KEY ("case_id") REFERENCES "public"."cases"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "prep_items" ADD CONSTRAINT "prep_items_artifact_id_artifacts_id_fk" FOREIGN KEY ("artifact_id") REFERENCES "public"."artifacts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "run_events" ADD CONSTRAINT "run_events_run_id_runs_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."runs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "runs" ADD CONSTRAINT "runs_case_id_cases_id_fk" FOREIGN KEY ("case_id") REFERENCES "public"."cases"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agent_traces" ADD CONSTRAINT "agent_traces_run_id_runs_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."runs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "contradictions" ADD CONSTRAINT "contradictions_run_id_runs_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."runs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "courtroom_sessions" ADD CONSTRAINT "courtroom_sessions_case_id_cases_id_fk" FOREIGN KEY ("case_id") REFERENCES "public"."cases"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "disclosure_gaps" ADD CONSTRAINT "disclosure_gaps_run_id_runs_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."runs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "jury_simulations" ADD CONSTRAINT "jury_simulations_run_id_runs_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."runs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "objection_events" ADD CONSTRAINT "objection_events_session_id_courtroom_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."courtroom_sessions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "plea_simulations" ADD CONSTRAINT "plea_simulations_run_id_runs_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."runs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "prosecution_runs" ADD CONSTRAINT "prosecution_runs_parent_run_id_runs_id_fk" FOREIGN KEY ("parent_run_id") REFERENCES "public"."runs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rights_findings" ADD CONSTRAINT "rights_findings_run_id_runs_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."runs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "run_branches" ADD CONSTRAINT "run_branches_parent_run_id_runs_id_fk" FOREIGN KEY ("parent_run_id") REFERENCES "public"."runs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "run_branches" ADD CONSTRAINT "run_branches_child_run_id_runs_id_fk" FOREIGN KEY ("child_run_id") REFERENCES "public"."runs"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agent_costs" ADD CONSTRAINT "agent_costs_run_id_runs_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."runs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agent_messages" ADD CONSTRAINT "agent_messages_run_id_runs_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."runs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit_bundles" ADD CONSTRAINT "audit_bundles_run_id_runs_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."runs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "model_routing_decisions" ADD CONSTRAINT "model_routing_decisions_run_id_runs_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."runs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "policy_drops" ADD CONSTRAINT "policy_drops_run_id_runs_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."runs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "quality_judgments" ADD CONSTRAINT "quality_judgments_run_id_runs_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."runs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "replay_cases" ADD CONSTRAINT "replay_cases_run_id_runs_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."runs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "speculative_branches" ADD CONSTRAINT "speculative_branches_run_id_runs_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."runs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "artifacts_run_subagent_idx" ON "artifacts" USING btree ("run_id","subagent");--> statement-breakpoint
CREATE UNIQUE INDEX "case_files_case_sha_uniq" ON "case_files" USING btree ("case_id","sha256");--> statement-breakpoint
CREATE INDEX "case_files_embedding_idx" ON "case_files" USING ivfflat ("embedding" vector_cosine_ops) WITH (lists=100);--> statement-breakpoint
CREATE INDEX "cases_user_updated_idx" ON "cases" USING btree ("user_id","updated_at" DESC NULLS LAST) WHERE "cases"."deleted_at" IS NULL;--> statement-breakpoint
CREATE INDEX "citations_run_kind_idx" ON "citations" USING btree ("run_id","artifact_kind");--> statement-breakpoint
CREATE UNIQUE INDEX "run_events_run_idx_uniq" ON "run_events" USING btree ("run_id","idx");--> statement-breakpoint
CREATE INDEX "run_events_run_idx" ON "run_events" USING btree ("run_id","idx");--> statement-breakpoint
CREATE INDEX "runs_case_started_idx" ON "runs" USING btree ("case_id","started_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "contradictions_run_idx" ON "contradictions" USING btree ("run_id");--> statement-breakpoint
CREATE INDEX "disclosure_gaps_run_idx" ON "disclosure_gaps" USING btree ("run_id");--> statement-breakpoint
CREATE INDEX "objection_events_session_idx" ON "objection_events" USING btree ("session_id","idx");--> statement-breakpoint
CREATE INDEX "rights_findings_run_idx" ON "rights_findings" USING btree ("run_id");--> statement-breakpoint
CREATE INDEX "run_branches_parent_idx" ON "run_branches" USING btree ("parent_run_id");--> statement-breakpoint
CREATE INDEX "agent_messages_run_idx" ON "agent_messages" USING btree ("run_id","idx");--> statement-breakpoint
CREATE INDEX "cost_ceilings_scope_idx" ON "cost_ceilings" USING btree ("scope","scope_id");--> statement-breakpoint
CREATE INDEX "model_routing_decisions_run_idx" ON "model_routing_decisions" USING btree ("run_id","idx");--> statement-breakpoint
CREATE UNIQUE INDEX "prompt_versions_key_version_uniq" ON "prompt_versions" USING btree ("prompt_key","version");--> statement-breakpoint
CREATE INDEX "prompt_versions_key_active_idx" ON "prompt_versions" USING btree ("prompt_key","is_active");--> statement-breakpoint
CREATE INDEX "semantic_cache_key_idx" ON "semantic_cache" USING btree ("cache_key");--> statement-breakpoint
CREATE INDEX "semantic_cache_last_used_idx" ON "semantic_cache" USING btree ("last_used_at");--> statement-breakpoint
CREATE INDEX "semantic_cache_embedding_idx" ON "semantic_cache" USING ivfflat ("prompt_embedding" vector_cosine_ops) WITH (lists=100);
-- run_events.idx must be strictly monotonic per run_id (replay correctness).
-- This trigger rejects any insert whose idx != COALESCE(max(idx)+1, 0).
CREATE OR REPLACE FUNCTION enforce_run_events_monotonic_idx()
RETURNS TRIGGER AS $$
DECLARE expected_idx integer;
BEGIN
  SELECT COALESCE(MAX(idx) + 1, 0) INTO expected_idx
    FROM run_events
    WHERE run_id = NEW.run_id;
  IF NEW.idx <> expected_idx THEN
    RAISE EXCEPTION 'run_events.idx must be monotonic per run_id (got %, expected %)',
      NEW.idx, expected_idx
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER run_events_monotonic_idx_trg
  BEFORE INSERT ON run_events
  FOR EACH ROW EXECUTE FUNCTION enforce_run_events_monotonic_idx();
