/**
 * G11 — Seed the canonical "State v. Johnson" demo case.
 *
 * Reproducibly recreates the 4-PDF + 1-transcript fixture under the
 * demo user (`demo_user_pd` / UUID …beef) so the 90-second demo journey
 * (spec Appendix A) can be re-run after any data reset. Every artifact
 * has a deterministic UUID + content-addressed sha256 so re-running this
 * script is idempotent and produces a byte-stable case the source
 * viewer can highlight against.
 *
 * Pivot drift: the spec's "Pick from Drive → STATE v. JOHNSON folder"
 * step is implemented as pre-loaded uploads. The web demo opens the
 * already-seeded case from Cases home and taps Start; the per-file OCR
 * progress overlay is a Drive-only ingest flow that the upload pipeline
 * skips. See `artifacts/briefcase-app/docs/demo-verification.md`.
 *
 * Run: pnpm --filter @workspace/api-server run seed:state-v-johnson
 */
import { db, cases, caseFiles } from "@workspace/db";
import { DEMO_USER_ID } from "@workspace/db/demo";
import { and, eq, sql } from "drizzle-orm";
import { PDFDocument, StandardFonts } from "pdf-lib";
import { putBytes } from "../src/lib/storage";

const CASE_ID = "00000000-0000-0000-0000-0000000a0001" as const;
const FILE_IDS = {
  policeReport: "00000000-0000-0000-0000-0000000a0002",
  bodycamLog: "00000000-0000-0000-0000-0000000a0003",
  labReport: "00000000-0000-0000-0000-0000000a0004",
  warrant: "00000000-0000-0000-0000-0000000a0005",
  transcript: "00000000-0000-0000-0000-0000000a0006",
} as const;

interface PdfFixture {
  id: string;
  name: string;
  /** One string per page. */
  pages: string[];
}

const POLICE_REPORT: PdfFixture = {
  id: FILE_IDS.policeReport,
  name: "police_report.pdf",
  pages: [
    [
      "STATE v. JOHNSON — INCIDENT REPORT",
      "Case No. 2025-CR-44021     Officer M. Rivera, Badge 4471",
      "Cook County Sheriff's Office, Patrol Division",
      "",
      "On March 14, 2025 at approximately 22:07 hours I initiated a",
      "traffic stop on a 2019 Toyota Camry, IL plate JON-714, traveling",
      "northbound on South Halsted Street near 79th. The vehicle was",
      "weaving and had a non-functioning rear license-plate lamp.",
      "",
      "The driver, defendant Marcus T. Johnson, was the sole occupant.",
      "At 22:09 I detected what I believed to be the odor of cannabis",
      "from the open driver window. I asked the defendant to step out.",
      "",
      "At 22:14 I commenced a probable-cause search of the vehicle. My",
      "body-worn camera was activated for the duration of the search.",
      "Inside a closed gym bag on the rear seat I located a black",
      "semi-automatic handgun and a small quantity of suspected",
      "cannabis weighing approximately 11 grams.",
    ].join("\n"),
    [
      "STATE v. JOHNSON — INCIDENT REPORT (cont.)",
      "",
      "At 22:38 the defendant was placed in the rear of patrol unit 217",
      "and transported to the 6th District station for booking. Chain",
      "of custody on the firearm and suspected cannabis was maintained",
      "continuously from the search through evidence intake at 23:21.",
      "",
      "Defendant declined to make a post-Miranda statement.",
      "",
      "Submitted: M. Rivera   03/15/2025   01:14",
    ].join("\n"),
  ],
};

const BODYCAM_LOG: PdfFixture = {
  id: FILE_IDS.bodycamLog,
  name: "bodycam_metadata.pdf",
  pages: [
    [
      "BODY-WORN CAMERA EVENT LOG",
      "Device: Axon Body 3   Serial: X3-44471",
      "Officer: M. Rivera, Badge 4471   Date: 2025-03-14",
      "",
      "22:04:11   ACTIVATE   user-initiated",
      "22:05:48   DEACTIVATE   user-initiated",
      "22:07:02   ACTIVATE   user-initiated",
      "22:07:55   DEACTIVATE   user-initiated",
      "22:25:33   ACTIVATE   user-initiated",
      "22:38:09   DEACTIVATE   user-initiated",
      "",
      "Total recorded duration during stop: 14 minutes 12 seconds.",
      "Gap between 22:07:55 and 22:25:33: 17 minutes 38 seconds.",
      "",
      "Generated by Axon Evidence Manager on 2025-03-15 02:01.",
    ].join("\n"),
  ],
};

const LAB_REPORT: PdfFixture = {
  id: FILE_IDS.labReport,
  name: "lab_report.pdf",
  pages: [
    [
      "ILLINOIS STATE POLICE FORENSIC SCIENCE LABORATORY",
      "Forest Park Regional Laboratory",
      "",
      "Case No. 2025-CR-44021      Lab No. FP-2025-08812",
      "Submitting Agency: Cook County Sheriff",
      "Analyst: Dr. Helena Chu, PhD     Report Date: 2025-04-02",
      "",
      "Item 1: Plant material, green-brown (~11.3 g gross).",
      "  Method: GC-MS confirmation per ILS-DRG-04 Rev. 7.",
      "  Result: delta-9-tetrahydrocannabinol detected. Confirmed cannabis.",
      "",
      "Item 2: Semi-automatic handgun, 9mm, serial obliterated.",
      "  Method: Visual + magnetic-particle examination.",
      "  Result: Serial number not recoverable. Functional test passed.",
      "",
      "Chain-of-custody intact. Items sealed and returned 2025-04-02.",
    ].join("\n"),
  ],
};

const WARRANT: PdfFixture = {
  id: FILE_IDS.warrant,
  name: "search_warrant_application.pdf",
  pages: [
    [
      "APPLICATION FOR SEARCH WARRANT",
      "Circuit Court of Cook County, Criminal Division",
      "",
      "Affiant: Officer M. Rivera, Badge 4471",
      "Premises: 2019 Toyota Camry, IL plate JON-714",
      "",
      "Probable cause: On 03/14/2025 at 22:09, affiant detected the",
      "odor of cannabis emanating from the open driver window of the",
      "above vehicle during a lawful traffic stop. Affiant requests",
      "authority to search the passenger compartment and any closed",
      "containers therein for controlled substances and contraband.",
    ].join("\n"),
    [
      "APPLICATION FOR SEARCH WARRANT (cont.)",
      "",
      "NOTE: This application was prepared after the search occurred.",
      "Filed 03/15/2025 09:47.",
      "",
      "Magistrate review: PENDING.",
    ].join("\n"),
  ],
};

const TRANSCRIPT_TEXT = [
  "INTERVIEW TRANSCRIPT — Marcus T. Johnson",
  "Cook County Public Defender's Office",
  "Date: 2025-03-18    Counsel: A. Patel, APD",
  "",
  "Q (Patel): Walk me through the stop. What time did the officer",
  "  pull you over?",
  "A (Johnson): It was right around 10 PM. Maybe 9:55. I had just",
  "  left my cousin's place on 78th.",
  "",
  "Q: Did you have anything in the car the officer would care about?",
  "A: No. The bag he pulled out — the gym bag — that was not mine.",
  "  I had never seen it. My cousin's friend had been in that car",
  "  earlier in the day.",
  "",
  "Q: Did the officer's bodycam appear to be on the whole time?",
  "A: No. I watched the red light. It was off when he walked up to",
  "  the window the second time. He turned it back on later, when he",
  "  was already searching the back.",
  "",
  "Q: Did you smell cannabis in the car at any point that night?",
  "A: No. I don't smoke. There was nothing in the car that smelled",
  "  like that.",
  "",
  "Q: Anything you want on the record?",
  "A: I never consented to a search. He asked, I said no. He stood",
  "  there for a few minutes and then said he smelled weed.",
  "",
  "Interview ends 14:32.",
].join("\n");

// Fixed epoch so pdf-lib emits stable CreationDate/ModDate metadata across
// reseed runs. Without this, every seed produces new bytes → new sha256 →
// duplicate objects under .local/storage/case-files. Pinning to the
// project pivot date keeps the content-address byte-stable.
const FIXED_PDF_DATE = new Date(Date.UTC(2026, 4, 2, 0, 0, 0));

async function buildPdf(fixture: PdfFixture): Promise<Buffer> {
  const doc = await PDFDocument.create();
  doc.setCreator("briefcase-seed");
  doc.setProducer("briefcase-seed");
  doc.setCreationDate(FIXED_PDF_DATE);
  doc.setModificationDate(FIXED_PDF_DATE);
  const font = await doc.embedFont(StandardFonts.Helvetica);
  for (const pageText of fixture.pages) {
    const page = doc.addPage([612, 792]); // US Letter
    const lines = pageText.split("\n");
    const fontSize = 11;
    const lineHeight = 16;
    const top = 760;
    const left = 56;
    lines.forEach((line, i) => {
      page.drawText(line, {
        x: left,
        y: top - i * lineHeight,
        size: fontSize,
        font,
      });
    });
  }
  const bytes = await doc.save({ useObjectStreams: false });
  return Buffer.from(bytes);
}

interface SeededFile {
  id: string;
  name: string;
  mime: string;
  bytes: Buffer;
  ocrText: string;
  pageCount: number;
}

async function buildAll(): Promise<SeededFile[]> {
  const pdfFixtures = [POLICE_REPORT, BODYCAM_LOG, LAB_REPORT, WARRANT];
  const out: SeededFile[] = [];
  for (const f of pdfFixtures) {
    const bytes = await buildPdf(f);
    out.push({
      id: f.id,
      name: f.name,
      mime: "application/pdf",
      bytes,
      ocrText: f.pages.join("\n\f\n"),
      pageCount: f.pages.length,
    });
  }
  out.push({
    id: FILE_IDS.transcript,
    name: "client_interview.txt",
    mime: "text/plain",
    bytes: Buffer.from(TRANSCRIPT_TEXT, "utf8"),
    ocrText: TRANSCRIPT_TEXT,
    pageCount: 1,
  });
  return out;
}

async function main(): Promise<void> {
  const files = await buildAll();

  await db
    .insert(cases)
    .values({
      id: CASE_ID,
      userId: DEMO_USER_ID,
      title: "State v. Johnson — suppression + bodycam gap",
      description:
        "Cook County, IL. Demo case for the 90-second pitch (spec Appendix A). " +
        "Defender prepares motion to suppress on warrantless search; flags 17-min " +
        "bodycam gap and post-search warrant application.",
      rolePack: "defender",
      status: "ready",
    })
    .onConflictDoUpdate({
      target: cases.id,
      set: {
        title: sql`EXCLUDED.title`,
        description: sql`EXCLUDED.description`,
        status: sql`EXCLUDED.status`,
      },
    });
  console.log(`seeded case: id=${CASE_ID}`);

  for (const f of files) {
    const stored = await putBytes(f.bytes);

    // Idempotent: existing row keyed by deterministic id, OR same
    // (caseId, sha256) pair. We always update the metadata + ocrText so
    // edits to the fixture text re-flow on next seed run.
    await db
      .insert(caseFiles)
      .values({
        id: f.id,
        caseId: CASE_ID,
        sourceType: "upload",
        name: f.name,
        mime: f.mime,
        sizeBytes: stored.sizeBytes,
        sha256: stored.sha256,
        ocrText: f.ocrText,
        detectedLanguage: "en",
      })
      .onConflictDoUpdate({
        target: caseFiles.id,
        set: {
          name: sql`EXCLUDED.name`,
          mime: sql`EXCLUDED.mime`,
          sizeBytes: sql`EXCLUDED.size_bytes`,
          sha256: sql`EXCLUDED.sha256`,
          ocrText: sql`EXCLUDED.ocr_text`,
          detectedLanguage: sql`EXCLUDED.detected_language`,
        },
      });
    console.log(
      `seeded ${f.name}  id=${f.id}  sha256=${stored.sha256.slice(0, 12)}…  size=${stored.sizeBytes}`,
    );
  }

  // Sanity: confirm the rows are queryable through the same path the
  // R-09 file route hits, so a misconfigured ownership join surfaces here
  // instead of mid-demo.
  const verify = await db
    .select({ id: caseFiles.id, name: caseFiles.name })
    .from(caseFiles)
    .where(and(eq(caseFiles.caseId, CASE_ID)));
  console.log(`\nverify: case has ${verify.length} files`);

  process.exit(0);
}

main().catch((err) => {
  console.error("seed-state-v-johnson failed:", err);
  process.exit(1);
});
